; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = MeteoPlaneRadar
default_envs = esp32-s3-touch-lcd-21

[env:esp32-s3-touch-lcd-21]
platform = espressif32
board = esp32-s3-devkitc1-n16r8
framework = arduino
board_build.arduino.memory_type = qio_opi
board_build.partitions = MeteoPlaneRadar/partitions.csv
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
build_flags = 
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
	-O2
lib_deps = 
	bblanchon/ArduinoJson @ ^7.1.0
	moononournation/GFX Library for Arduino @ ^1.5.4
	bitbank2/PNGdec @ ^1.0.1
	olikraus/U8g2_for_Adafruit_GFX@^1.8.0
monitor_speed = 115200
